## **Row & column Selection & Indexing and setting value using pandas**

### **column selection using pandas**

In [3]:
# Importing necessary libraries
import pandas as pd 
import os 
from tabulate import tabulate 
from google.colab import drive

In [4]:
# Mounding google drive 
drive.mount("/content/drive/")

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [5]:
# checking the file path 
!ls /content/drive/MyDrive/raw_dataset/retail_dataset

raw_customers.csv	     raw_products.csv  raw_sales_transactions.csv
raw_employees.csv	     raw_returns.csv   raw_stores.csv
raw_inventory_snapshots.csv  raw_reviews.csv

In [7]:
# reading data using pandas
df = pd.read_csv("/content/drive/MyDrive/raw_dataset/retail_dataset/raw_customers.csv")

In [8]:
# Data Decomposition
customer_identity = ['customer_id', 'title', 'first_name', 'last_name', 'full_name', 'gender', 'is_active']
customer_address = ['customer_id', 'address', 'city', 'state_abbr', 'state_full', 'zip_code', 'country', 'region']
customer_content = ['customer_id', 'email', 'phone']
customer_business_info = ['customer_id','customer_segment', 'loyalty_points','preferred_channel', 'annual_income_usd', 'company' ]
customer_dates = ['customer_id','date_of_birth', 'age', 'account_created_date']

In [9]:
# defining the data frame for eatch decomposition 
customer_identity_df = df[customer_identity]
customer_address_df = df[customer_address]
customer_content_df = df[customer_content]
customer_business_info_df = df[customer_business_info]
customer_dates_df = df[customer_dates]

In [56]:
# checking the issues in customer identity dataframe 
print(
    tabulate(
        customer_identity_df.sample(frac=0.02), 
        headers='keys', 
        tablefmt='simple_grid'
    )
)

┌─────┬───────────────┬─────────┬──────────────┬─────────────┬─────────────────────┬───────────────────┬─────────────┐
│     │   customer_id │ title   │ first_name   │ last_name   │ full_name           │ gender            │ is_active   │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│ 631 │          1529 │ nan     │ Susan        │ lopez       │ Susan Lopez         │ FEMALE            │ FALSE       │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│  50 │          1070 │ nan     │ Diane        │ Wright      │ Diane Wright        │ female            │ 1           │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│  87 │          1326 │ Mr.     │ David        │ Williams    │ Mr. David Williams  │ F                 │ TRUE        │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│ 637 │          1496 │ Ms.     │ Cynthia      │ Reyes       │ Ms. Cynthia Reyes   │ Prefer not to say │ Inactive    │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│ 185 │          1322 │ nan     │ William      │ Walker      │ William Walker      │ female            │ FALSE       │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│ 541 │          1308 │ nan     │ Justin       │ Ortiz       │ Justin Ortiz        │ Prefer not to say │ N           │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│ 508 │          9022 │ nan     │ Wiliam       │ Alvarez     │ William Alvarez     │ Non-Binary        │ N           │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│ 503 │          1073 │ Mrs.    │ Jessica      │ Martin      │ Mrs. Jessica Martin │ Other             │ 1           │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│ 608 │          1029 │ nan     │ Kevin        │ Diaz        │ Kevin Diaz          │ Non-Binary        │ No          │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│ 169 │          1535 │ nan     │ Rebecca      │ Brown       │ Rebecca Brown       │ FEMALE            │ Inactive    │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│ 630 │          1399 │ nan     │ Emma         │ Perez       │ Emma Perez          │ Male              │ Yes         │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│ 276 │          1406 │ nan     │ Betty        │ Edwards     │ Betty Edwards       │ F                 │ FALSE       │
├─────┼───────────────┼─────────┼──────────────┼─────────────┼─────────────────────┼───────────────────┼─────────────┤
│ 171 │          1092 │ nan     │ Katherine    │ Nguyen      │ Katherine Nguyen    │ M                 │ FALSE       │
└─────┴───────────────┴─────────┴──────────────┴─────────────┴─────────────────────┴───────────────────┴─────────────┘

In [57]:
# checking the issues in customer address dataframe 
print(
    tabulate(customer_address_df.sample(frac=0.02),
            headers='keys', 
            tablefmt='simple_grid'
        )
)

┌─────┬───────────────┬────────────────────────┬───────────────┬──────────────┬────────────────┬────────────┬───────────────┬──────────┐
│     │   customer_id │ address                │ city          │ state_abbr   │ state_full     │   zip_code │ country       │ region   │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 564 │          1208 │ 52 High St             │ MEMPHIS       │ TN           │ Tennessee      │      52229 │ USA           │ South    │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 508 │          9022 │ 5252 Park Ave          │ Milwakee      │ WI           │ Wisconsin      │      26165 │ US            │ Midwest  │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 485 │          9920 │ 4318 Broadway Apt 28   │ san jose      │ CA           │ California     │      36006 │ U.S.A         │ West     │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 320 │          1266 │ 4701 River Rd          │ Oklahoma City │ OK           │ Oklahoma       │      20683 │ U.S.A         │ South    │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 311 │          1256 │ 4104 Cedar Blvd Apt 48 │ Raleigh       │ NC           │ North Carolina │      19552 │ U.S.A         │ South    │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 430 │          1422 │ 4073 Sunset Dr         │ MINNEAPOLIS   │ MN           │ Minnesota      │      94884 │ US            │ Midwest  │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 281 │          1413 │ 2440 Maple Dr          │ Fort Worth    │ TX           │ Texas          │      18398 │ US            │ South    │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 217 │          1426 │ 3172 Elm St            │ San Francisco │ CA           │ California     │      68648 │ United States │ West     │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 233 │          1570 │ 8342 Union St Apt 5    │ San Antonio   │ TX           │ Texas          │      50811 │ USA           │ South    │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 131 │          1189 │ 995 Oak Ave            │ san antonio   │ TX           │ Texas          │      18523 │ US            │ South    │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 221 │          1505 │ 294 Hill Rd            │ Fort Worth    │ TX           │ Texas          │      62111 │ USA           │ South    │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 412 │          1469 │ 8746 Hill Rd           │ Louisville    │ KY           │ Kentucky       │      76470 │ US            │ South    │
├─────┼───────────────┼────────────────────────┼───────────────┼──────────────┼────────────────┼────────────┼───────────────┼──────────┤
│ 556 │          1184 │ 9602 Park Ave          │ San Antonio   │ TX           │ Texas          │      76115 │ U.S.A         │ South    │
└─────┴───────────────┴────────────────────────┴───────────────┴──────────────┴────────────────┴────────────┴───────────────┴──────────┘

In [58]:
# checking the issues in customer content dataframe 
print(
    tabulate(
        customer_content_df.sample(frac=0.02), 
        headers='keys', 
        tablefmt='simple_grid'
    )
)

┌─────┬───────────────┬────────────────────────────────────┬────────────────┐
│     │   customer_id │ email                              │ phone          │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 264 │          1309 │ heather_young146@@@icloud.com      │ 5187362681     │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 485 │          9920 │ JULIE_WILLIAMS@MAIL.COM            │ 23.391.5087    │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 230 │          1518 │ cynthiadiaz@outlook.com            │ 350-385-8812   │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 127 │          1084 │ jonathan_richardson268@outlook.com │ 258.814.7620   │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 242 │          1114 │ jessica.torres58@mail.com          │ (396) 456-7251 │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 140 │          1048 │ betty.myers@protonmail.com         │ 214.954.6523   │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 347 │          9195 │ BRENDAJOHNSON@OUTLOOK.COM          │ nan            │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 543 │          1531 │ daniel_hill587@protonmail.com      │ 3695675807     │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 424 │          1561 │ gregorycooper658@mail.com          │ 788.813.9789   │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 123 │          1429 │ kevin.morris@outlook.com           │ 8066603666     │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 232 │          1165 │ scott.jimenez994@protonmail.com    │ 257.702.9740   │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 158 │          1033 │ justin_chavez852@yahoo.com         │ +12928299307   │
├─────┼───────────────┼────────────────────────────────────┼────────────────┤
│ 426 │          1568 │ carol.murphy@gmail.com             │ (354) 443-7539 │
└─────┴───────────────┴────────────────────────────────────┴────────────────┘

In [59]:
# checking the issues in customer business information dataframe 
print(
    tabulate(
        customer_business_info_df.sample(frac=0.02), 
        headers='keys', 
        tablefmt='simple_grid'
    )
)

┌─────┬───────────────┬────────────────────┬──────────────────┬─────────────────────┬─────────────────────┬───────────────────────────┐
│     │   customer_id │ customer_segment   │   loyalty_points │ preferred_channel   │   annual_income_usd │ company                   │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│ 609 │          1329 │ Bronze             │             1502 │ online              │                 nan │ nan                       │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│ 295 │          1411 │ Bronze             │             4116 │ Online              │                 nan │ Global Premier Services   │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│ 599 │          1069 │ Bronze             │              207 │ catalog             │              160586 │ nan                       │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│ 380 │          1036 │ Gold               │            12965 │ Catalog             │              142598 │ nan                       │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│ 632 │          1375 │ Silver             │            13554 │ PHONE               │               84146 │ Global Premier Associates │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│ 267 │          1577 │ Silver             │              nan │ online              │               51189 │ nan                       │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│  22 │          1282 │ Gold               │             3575 │ in-store            │                 nan │ nan                       │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│ 533 │          1484 │ Bronze             │             6973 │ mobile              │              211742 │ nan                       │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│ 486 │          1248 │ Bronze             │             5162 │ Online              │              199596 │ Gold Tech Corp            │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│ 565 │          1005 │ Gold               │             6939 │ Phone               │              215896 │ nan                       │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│ 103 │          1333 │ Bronze             │            11441 │ Store               │              238207 │ Central Elite Solutions   │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│ 349 │          1414 │ Bronze             │            14951 │ ONLINE              │               77078 │ Metro Future LLC          │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────────────────┤
│ 437 │          1512 │ Gold               │              241 │ In-Store            │               80911 │ nan                       │
└─────┴───────────────┴────────────────────┴──────────────────┴─────────────────────┴─────────────────────┴───────────────────────────┘

In [60]:
# checking the issues in customer date's dataframe 
print(
    tabulate(
        customer_dates_df.sample(frac=0.02), 
        headers='keys', 
        tablefmt='simple_grid'
    )
)

┌─────┬───────────────┬─────────────────┬───────┬────────────────────────┐
│     │   customer_id │ date_of_birth   │   age │ account_created_date   │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│ 454 │          9530 │ 2001-04-23      │    23 │ 27-07-2023             │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│ 112 │          1403 │ 1976/06/06      │    48 │ Apr 15, 2020           │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│ 185 │          1322 │ 1989/09/25      │    35 │ 2018/10/12             │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│ 461 │          1364 │ 1983-10-24      │    41 │ May 14, 2021           │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│ 193 │          1157 │ 1961-06-21      │    63 │ 12/07/2023             │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│ 397 │          1409 │ August 24, 1964 │    60 │ May 29, 2020           │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│  14 │          1310 │ Jan 23, 1987    │    37 │ June 22, 2023          │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│ 427 │          1071 │ 21/09/1976      │    48 │ 2019-09-09             │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│ 489 │          1179 │ 01-05-1988      │    36 │ 19-03-2020             │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│ 101 │          1331 │ Feb 07, 2001    │    23 │ 18/03/2023             │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│ 421 │          1101 │ 28-12-1989      │    35 │ January 28, 2018       │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│ 189 │          1155 │ 28-12-1982      │    42 │ 18-05-2021             │
├─────┼───────────────┼─────────────────┼───────┼────────────────────────┤
│ 291 │          1520 │ 1968/11/22      │    56 │ Mar 22, 2019           │
└─────┴───────────────┴─────────────────┴───────┴────────────────────────┘

In [55]:
# checking the all numerici data type in the dataset 
print(
    tabulate(
        df.select_dtypes(include='number').sample(frac=0.02), 
        headers='keys', 
        tablefmt='simple_grid'
    )
)

┌─────┬───────────────┬───────┬────────────┬──────────────────┬─────────────────────┐
│     │   customer_id │   age │   zip_code │   loyalty_points │   annual_income_usd │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│ 197 │          1225 │    64 │      86449 │            11839 │               82839 │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│ 573 │          1339 │    37 │      25738 │             2323 │              149912 │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│ 491 │          1348 │    38 │      99415 │             7689 │               90953 │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│ 561 │          1528 │    64 │      90546 │              817 │              166228 │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│ 290 │          9896 │    29 │      18973 │             2238 │               74227 │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│ 419 │          1235 │    44 │      71599 │            10489 │              231978 │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│ 514 │          9024 │    36 │      94604 │             1776 │                 nan │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│ 408 │          1125 │    48 │      90879 │            11269 │              184365 │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│   3 │          1449 │    48 │      60507 │             7108 │              231000 │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│ 461 │          1364 │    41 │      89791 │             5163 │              239102 │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│ 116 │          1345 │    43 │      58060 │              336 │               33791 │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│ 171 │          1092 │    28 │      10568 │             9064 │              206355 │
├─────┼───────────────┼───────┼────────────┼──────────────────┼─────────────────────┤
│  54 │          1126 │    44 │      77760 │             7595 │              128040 │
└─────┴───────────────┴───────┴────────────┴──────────────────┴─────────────────────┘

In [54]:
print(
    tabulate(
        customer_business_info_df.select_dtypes(include='object').sample(frac=0.02), 
        headers='keys', 
        tablefmt='simple_grid'
    )
)

┌─────┬────────────────────┬─────────────────────┬────────────────────────────┐
│     │ customer_segment   │ preferred_channel   │ company                    │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 261 │ Silver             │ In-Store            │ Summit Premier Enterprises │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 570 │ Bronze             │ IN STORE            │ nan                        │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 171 │ Platinum           │ in-store            │ nan                        │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 453 │ Silver             │ Store               │ nan                        │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 461 │ Silver             │ online              │ nan                        │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 138 │ Bronze             │ ONLINE              │ nan                        │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 426 │ Platinum           │ Phone               │ nan                        │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 103 │ Bronze             │ Store               │ Central Elite Solutions    │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 155 │ Gold               │ Store               │ nan                        │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 606 │ Silver             │ Phone               │ nan                        │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 317 │ Gold               │ Mobile App          │ Global United Services     │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 333 │ Bronze             │ Catalog             │ nan                        │
├─────┼────────────────────┼─────────────────────┼────────────────────────────┤
│ 176 │ Bronze             │ IN STORE            │ nan                        │
└─────┴────────────────────┴─────────────────────┴────────────────────────────┘

### **Row Selection using pandas**

In [61]:
# Slicing by the positin 
print(
    tabulate(
        customer_identity_df[2:8], 
        headers='keys', 
        tablefmt='simple_grid'
    )
)

┌────┬───────────────┬─────────┬──────────────┬─────────────┬──────────────────────────┬────────────┬─────────────┐
│    │   customer_id │ title   │ first_name   │ last_name   │ full_name                │ gender     │ is_active   │
├────┼───────────────┼─────────┼──────────────┼─────────────┼──────────────────────────┼────────────┼─────────────┤
│  2 │          1457 │ nan     │ Stephen      │ king        │ Stephen King             │ male       │ 0           │
├────┼───────────────┼─────────┼──────────────┼─────────────┼──────────────────────────┼────────────┼─────────────┤
│  3 │          1449 │ Dr.     │ Jennifer     │ Roberts     │ Dr. Jennifer Roberts     │ FEMALE     │ N           │
├────┼───────────────┼─────────┼──────────────┼─────────────┼──────────────────────────┼────────────┼─────────────┤
│  4 │          1081 │ Mrs.    │ Catherine    │ Rodriguez   │ Mrs. Catherine Rodriguez │ non-binary │ 0           │
├────┼───────────────┼─────────┼──────────────┼─────────────┼──────────────────────────┼────────────┼─────────────┤
│  5 │          1247 │ nan     │ rachel       │ Flores      │ Rachel Flores            │ Non-Binary │ N           │
├────┼───────────────┼─────────┼──────────────┼─────────────┼──────────────────────────┼────────────┼─────────────┤
│  6 │          1138 │ nan     │ Gary         │ Kelly       │ Gary Kelly               │ MALE       │ 1           │
├────┼───────────────┼─────────┼──────────────┼─────────────┼──────────────────────────┼────────────┼─────────────┤
│  7 │          1517 │ Ms.     │ Rachel       │ Clark       │ Ms. Rachel Clark         │ Non-Binary │ Y           │
└────┴───────────────┴─────────┴──────────────┴─────────────┴──────────────────────────┴────────────┴─────────────┘

In [53]:
# Boolean mask 
print(
    tabulate(
        customer_dates_df[customer_dates_df['age'] > 50].sample(frac=0.05),
        headers='keys',
        tablefmt='simple_grid'
    )
)

┌─────┬───────────────┬──────────────────┬───────┬────────────────────────┐
│     │   customer_id │ date_of_birth    │   age │ account_created_date   │
├─────┼───────────────┼──────────────────┼───────┼────────────────────────┤
│ 429 │          1430 │ 1970-04-26       │    54 │ 2023/09/22             │
├─────┼───────────────┼──────────────────┼───────┼────────────────────────┤
│  71 │          1298 │ 31-01-1967       │    57 │ 15/08/2018             │
├─────┼───────────────┼──────────────────┼───────┼────────────────────────┤
│ 420 │          1516 │ 1962/09/29       │    62 │ 07/07/2018             │
├─────┼───────────────┼──────────────────┼───────┼────────────────────────┤
│  88 │          1502 │ 1960-12-03       │    64 │ 03/07/2018             │
├─────┼───────────────┼──────────────────┼───────┼────────────────────────┤
│ 218 │          1472 │ 03/05/1967       │    57 │ 08/09/2022             │
├─────┼───────────────┼──────────────────┼───────┼────────────────────────┤
│  33 │          1082 │ 03/23/1970       │    54 │ 2020-10-18             │
├─────┼───────────────┼──────────────────┼───────┼────────────────────────┤
│ 236 │          1486 │ October 03, 1968 │    56 │ Dec 29, 2022           │
├─────┼───────────────┼──────────────────┼───────┼────────────────────────┤
│  76 │          9741 │ May 08, 1968     │    56 │ 2021/11/10             │
├─────┼───────────────┼──────────────────┼───────┼────────────────────────┤
│ 457 │          1396 │ 04/23/1970       │    54 │ 19/05/2022             │
├─────┼───────────────┼──────────────────┼───────┼────────────────────────┤
│ 267 │          1577 │ October 03, 1963 │    61 │ 2023-08-19             │
└─────┴───────────────┴──────────────────┴───────┴────────────────────────┘

### **.loc — label-based (inclusive on both ends)**

In [10]:
# selecting row with 0 inclusive lebel 
df.loc[0]

customer_id                                   1099
title                                          NaN
first_name                                Nicholas
last_name                                   Nelson
full_name                          Nicholas Nelson
gender                           Prefer not to say
date_of_birth                           05-09-1968
age                                             56
email                   nicholas_nelson@icloud.com
phone                                 957.856.8145
address                               2201 Mill Rd
city                                       Dallas
state                                        Texas
state_abbr                                      TX
state_full                                   Texas
zip_code                                     72908
country                                      U.S.A
region                                       South
customer_segment                            Silver
loyalty_points                              7296.0
is_active                                      Yes
account_created_date                  Dec 21, 2019
preferred_channel                           ONLINE
annual_income_usd                         245670.0
company                                        NaN
Name: 0, dtype: object

In [50]:
# rows 0-5, cols name to score
print(
    tabulate(
        customer_dates_df.loc[0:5, 'customer_id' : 'date_of_birth'],
        headers='keys',
        tablefmt='simple_grid'
    )
)

┌────┬───────────────┬───────────────────┐
│    │   customer_id │ date_of_birth     │
├────┼───────────────┼───────────────────┤
│  0 │          1099 │ 05-09-1968        │
├────┼───────────────┼───────────────────┤
│  1 │          1170 │ 1994/02/28        │
├────┼───────────────┼───────────────────┤
│  2 │          1457 │ 1969/09/20        │
├────┼───────────────┼───────────────────┤
│  3 │          1449 │ 22/03/1976        │
├────┼───────────────┼───────────────────┤
│  4 │          1081 │ February 20, 2001 │
├────┼───────────────┼───────────────────┤
│  5 │          1247 │ 2000-02-08        │
└────┴───────────────┴───────────────────┘

In [65]:
# specific rows & cols
print(
    tabulate(
        customer_identity_df.loc[[1, 3, 5, 9 , 33], ['customer_id', 'first_name']],
        headers='keys',
        tablefmt='simple_grid'
    )
)

┌────┬───────────────┬──────────────┐
│    │   customer_id │ first_name   │
├────┼───────────────┼──────────────┤
│  1 │          1170 │ Thomas       │
├────┼───────────────┼──────────────┤
│  3 │          1449 │ Jennifer     │
├────┼───────────────┼──────────────┤
│  5 │          1247 │ rachel       │
├────┼───────────────┼──────────────┤
│  9 │          1597 │ Nicole       │
├────┼───────────────┼──────────────┤
│ 33 │          1082 │ Julie        │
└────┴───────────────┴──────────────┘

### **.iloc — integer position-based (exclusive end)**

In [24]:
# Returning the last row from the table 
print(
    tabulate(
        customer_content_df.iloc[[-1]],
        headers='keys',
        tablefmt='simple_grid'
    )
)

┌─────┬───────────────┬──────────────────────────┬──────────────┐
│     │   customer_id │ email                    │ phone        │
├─────┼───────────────┼──────────────────────────┼──────────────┤
│ 639 │          1573 │ daniel.sanders@yahoo.com │ 778.765.2176 │
└─────┴───────────────┴──────────────────────────┴──────────────┘

In [30]:
# Returning the last column from the table 
customer_content_df.iloc[: , -1].head(10)

0      957.856.8145
1      387.236.8704
2      958-779-3527
3        5522085952
4      +15526205327
5      541.254.8230
6      717.278.5552
7        2304699470
8      617-904-2743
9    (297) 887-1798
Name: phone, dtype: object

## **.at / .iat — single value (fast scalar access)**

In [41]:
# at is the label base slicing for single value

In [32]:
customer_identity_df.at[0 , 'first_name']

'Nicholas'

In [37]:
customer_identity_df.at[544 , 'full_name']

'Prof. Larry Rodriguez'

In [40]:
customer_identity_df.at[122 , 'gender']

'Non-Binary'

In [42]:
# iat is the position base slicing for single value

In [55]:
customer_identity_df.iat[122 , 1]

'Mrs.'

In [56]:
customer_identity_df.iat[122 , 2]

'brenda'

In [57]:
customer_identity_df.iat[122 , 3]

'Adams'

### **.xs — cross-section (great for MultiIndex)**

In [64]:
import pandas as pd

df = pd.DataFrame({
    "customer_segment": ["bronze", "bronze", "silver", "gold"],
    "city": ["Patna", "Delhi", "Patna", "Mumbai"],
    "sales": [100, 200, 300, 400]
})

df = df.set_index(["customer_segment", "city"])

df.xs('bronze', level='customer_segment')

       sales
city
Patna    100
Delhi    200